import streamlit as st
import streamlit.components.v1 as components
import json
import math
import pandas as pd
from typing import List, Dict

# Updated imports
from utils.data_loader import load_game_data
from utils.utils import calculate_steps
from utils.export import export_gearset
from gear_optimizer import GearOptimizer, OPTIMAZATION_TARGET
from models import Equipment

# --- Page Config ---
st.set_page_config(
    page_title="WalkScape Gear Optimizer",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- Custom CSS to reduce padding ---
st.markdown("""
    <style>
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
            padding-left: 2rem;
            padding-right: 2rem;
        }
        /* Make the iframe container tighter */
        iframe {
            width: 100%;
        }
    </style>
""", unsafe_allow_html=True)

# --- Helpers ---
def get_xp_for_level(level: int) -> int:
    total = 0
    for i in range(1, level):
        total += math.floor(i + 300 * (2 ** (i / 7.0)))
    return math.floor(total / 4)

def calculate_level_from_xp(current_xp: int) -> int:
    for lvl in range(1, 150):
        if get_xp_for_level(lvl + 1) > current_xp:
            return lvl
    return 150

def calculate_char_level_from_steps(current_steps: int) -> int:
    for lvl in range(1, 120):
        xp_req_standard = get_xp_for_level(lvl + 1)
        steps_req = math.floor(xp_req_standard) * 4.6
        if steps_req > current_steps:
            return lvl
    return 120

@st.cache_data
def load_data():
    items_path = "game_data/wiki_export/autogenerated/equipment.json"
    act_path = "game_data/wiki_export/autogenerated/activities.json"
    rec_path = "game_data/wiki_export/autogenerated/recipes.json"
    loc_path = "game_data/wiki_export/autogenerated/locations.json"
    return load_game_data(items_path, act_path, rec_path, loc_path)

def filter_user_items(all_items: List[Equipment], user_data: Dict) -> List[Equipment]:
    try:
        owned_ids = set()
        def add_keys(container_name):
            container = user_data.get(container_name, {})
            if isinstance(container, dict):
                for k in container.keys(): owned_ids.add(str(k).lower())
            elif isinstance(container, list):
                for k in container: owned_ids.add(str(k).lower())

        add_keys("bank")
        add_keys("inventory")
        if "gear" in user_data:
            gear = user_data["gear"]
            if isinstance(gear, dict):
                for v in gear.values(): 
                    if v: owned_ids.add(str(v).lower())
        
        filtered_items = []
        for item in all_items:
            candidates = set()
            candidates.add(item.id.lower())
            if item.wiki_slug: candidates.add(item.wiki_slug.lower())
            if item.name: candidates.add(item.name.lower())
            
            base_id = item.id.lower()
            suffixes = ["_common", "_uncommon", "_rare", "_epic", "_legendary", "_ethereal", "_normal"]
            for s in suffixes:
                if base_id.endswith(s): candidates.add(base_id.replace(s, ""))
            
            if not owned_ids.isdisjoint(candidates):
                filtered_items.append(item)
        return filtered_items
    except Exception:
        return all_items

# --- Main App ---
def main():
    # Load Data
    all_items_raw, activities, recipes, locations = load_data()   
    WIKI_URL = "https://gear.walkscape.app"

    st.title("🛡️ WalkScape Gear Optimizer")

    # --- Top Bar: Inputs & Settings ---
    with st.container():
        # User Data Section
        with st.expander("📂 User Save Data & Settings", expanded=True):
            col_json, col_opts = st.columns([3, 1])
            with col_json:
                # Note: 'text_area' requires Ctrl+Enter or Click Outside to submit. 
                # This is a strict limitation of Streamlit's frontend event model.
                user_json_input = st.text_area(
                    "Paste User JSON", 
                    height=70, 
                    placeholder='{"name": "...", "skills": {...}}'
                )
            
            user_data = None
            calculated_char_lvl = 99
            user_skills_map = {}
            valid_json = False

            if user_json_input.strip():
                try:
                    user_data = json.loads(user_json_input)
                    valid_json = True
                    steps = user_data.get("steps", 0)
                    calculated_char_lvl = calculate_char_level_from_steps(steps)
                    user_skills_map = user_data.get("skills", {})
                    st.success(f"Loaded: {user_data.get('name', 'Player')}")
                except json.JSONDecodeError:
                    st.error("Invalid JSON")
            
            with col_opts:
                st.write("") # Spacer
                use_owned = st.checkbox("Only use owned items", value=valid_json)

        # Controls Section
        c1, c2, c3 = st.columns([2, 1, 1])
        
        with c1:
            act_map = {a.name: a for a in activities}
            act_names = sorted(list(act_map.keys()))
            selected_act_name = st.selectbox("Select Activity", options=act_names, index=None, placeholder="Search activity...")
        
        with c2:
            target_options = {t.name.replace('_', ' ').title(): t for t in OPTIMAZATION_TARGET}
            selected_target_key = st.selectbox("Target Stat", options=list(target_options.keys()))
            selected_target = target_options[selected_target_key]
        
        with c3:
            st.write("") # Spacer
            st.write("")
            run_opt = st.button("🚀 Optimize", type="primary", use_container_width=True)

    st.divider()

    # --- Main Layout ---
    # Left: Results (1) | Right: Wiki (2.5) -> More space for Wiki
    left_col, right_col = st.columns([1, 2.5])

    # --- RIGHT COLUMN: WIKI ---
    with right_col:
        st.subheader("Wiki Reference")
        # Increased height to 1200 as requested
        components.iframe(WIKI_URL, height=1200, scrolling=True)

    # --- LEFT COLUMN: OPTIMIZER RESULTS ---
    with left_col:
        st.subheader("Results")

        if use_owned and user_data:
            available_items = filter_user_items(all_items_raw, user_data)
        else:
            available_items = all_items_raw

        if run_opt and selected_act_name:
            activity = act_map[selected_act_name]
            player_lvl = calculated_char_lvl if valid_json else 99
            
            final_skill_lvl = 99
            if valid_json and activity.primary_skill:
                skill_key = activity.primary_skill.lower()
                skill_xp = user_skills_map.get(skill_key, 0)
                final_skill_lvl = calculate_level_from_xp(skill_xp)
            
            with st.spinner(f"Optimizing {selected_act_name}..."):
                optimizer = GearOptimizer(available_items, all_locations=locations)
                best_gear = optimizer.optimize(
                    activity, 
                    player_level=player_lvl, 
                    player_skill_level=final_skill_lvl,
                    optimazation_target=selected_target
                )

            # --- Stats Calculation ---
            loc_id = activity.locations[0] if activity.locations else None
            loc_tags = set()
            for loc in locations:
                if loc.id == loc_id:
                    loc_tags = set(loc.tags)
                    break
                    
            context = {
                "skill": activity.primary_skill,
                "location_id": loc_id,
                "location_tags": loc_tags,
                "activity_id": activity.id
            }

            stats = best_gear.get_stats(context)
            final_steps = calculate_steps(
                activity, final_skill_lvl, 
                stats.get("work_efficiency", 0), 
                stats.get("flat_step_reduction", 0), 
                stats.get("percent_step_reduction", 0)
            )
            
            xp_mult = 1.0 + stats.get("xp_percent", 0)
            total_xp = ((activity.base_xp or 0 * xp_mult) + stats.get("flat_xp", 0)) * (1.0 + stats.get("double_action", 0))

            # --- Stats Grid ---
            m1, m2 = st.columns(2)
            m3, m4 = st.columns(2)
            m1.metric("Steps", f"{final_steps}", delta=f"{activity.base_steps}", delta_color="inverse")
            m2.metric("XP", f"{total_xp:.1f}")
            m3.metric("Dbl Action", f"{stats.get('double_action', 0)*100:.0f}%")
            m4.metric("Work Eff", f"{stats.get('work_efficiency', 0)*100:.0f}%")

            st.divider()

            # --- Loadout Table ---
            st.markdown("#### 🎒 Loadout")
            loadout_data = []
            
            def add_row(slot, item):
                name = item.name if item else "-"
                qual = item.quality if item else ""
                loadout_data.append({"Slot": slot, "Item": name, "Quality": qual})

            add_row("Head", best_gear.head)
            add_row("Chest", best_gear.chest)
            add_row("Legs", best_gear.legs)
            add_row("Feet", best_gear.feet)
            add_row("Back", best_gear.back)
            add_row("Cape", best_gear.cape)
            add_row("Neck", best_gear.neck)
            add_row("Hands", best_gear.hands)
            add_row("Primary", best_gear.primary)   
            add_row("Secondary", best_gear.secondary)
            
            if best_gear.rings:
                add_row("Ring 1", best_gear.rings[0])
                if len(best_gear.rings) > 1: add_row("Ring 2", best_gear.rings[1])
            
            if best_gear.tools:
                for i, tool in enumerate(best_gear.tools):
                    add_row(f"Tool {i+1}", tool)

            df = pd.DataFrame(loadout_data)
            st.dataframe(
                df, 
                column_config={
                    "Slot": st.column_config.TextColumn("Slot", width="small"),
                    "Item": st.column_config.TextColumn("Item", width="medium"),
                    "Quality": st.column_config.TextColumn("Qual", width="small"),
                },
                hide_index=True,
                use_container_width=True
            )

            # --- Export Section (Highlighted) ---
            st.markdown("---")
            
            # Use st.success to give it a green background for attention
            with st.success("✅ **Export Ready**"):
                export_json = export_gearset(best_gear)
                st.caption("Hover over the top-right of the code block to copy!")
                st.code(export_json, language="json")

        elif not selected_act_name:
            st.info("👈 Select an activity to start.")
            
        else:
            st.write("Ready.")

if __name__ == "__main__":
    main()