import streamlit as st
import streamlit.components.v1 as components
import json
import math
import pandas as pd
from typing import List, Dict, Optional
from collections import Counter

# Updated imports
from utils.data_loader import load_game_data
from utils.utils import calculate_steps
from utils.export import export_gearset
from gear_optimizer import GearOptimizer, OPTIMAZATION_TARGET
from models import Equipment, GearSet, Collectible, Modifier, Condition

# --- Page Config ---
st.set_page_config(
    page_title="WalkScape Gear Optimizer",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- Custom CSS ---
st.markdown("""
    <style>
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
            padding-left: 2rem;
            padding-right: 2rem;
        }
        iframe { width: 100%; }
    </style>
""", unsafe_allow_html=True)

# --- Helpers ---
def get_xp_for_level(level: int) -> int:
    total = 0
    for i in range(1, level):
        total += math.floor(i + 300 * (2 ** (i / 7.0)))
    return math.floor(total / 4)

def calculate_level_from_xp(current_xp: int) -> int:
    for lvl in range(1, 150):
        if get_xp_for_level(lvl + 1) > current_xp:
            return lvl
    return 150

def calculate_char_level_from_steps(current_steps: int) -> int:
    for lvl in range(1, 120):
        xp_req_standard = get_xp_for_level(lvl + 1)
        steps_req = math.floor(xp_req_standard) * 4.6
        if steps_req > current_steps:
            return lvl
    return 120

@st.cache_data
def load_data():
    items_path = "game_data/wiki_export/autogenerated/equipment.json"
    act_path = "game_data/wiki_export/autogenerated/activities.json"
    rec_path = "game_data/wiki_export/autogenerated/recipes.json"
    loc_path = "game_data/wiki_export/autogenerated/locations.json"
    return load_game_data(items_path, act_path, rec_path, loc_path)

@st.cache_data
def load_collectibles_data() -> List[Collectible]:
    path = "game_data/wiki_export/autogenerated/collectibles.json"
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return [Collectible(**entry) for entry in data]
    except FileNotFoundError:
        print(f"Warning: {path} not found.")
        return []

def extract_user_counts(user_data: Dict) -> Dict[str, int]:
    counts = Counter()
    for container in ["bank", "inventory"]:
        data = user_data.get(container, {})
        if isinstance(data, dict):
            for k, v in data.items():
                counts[str(k).lower()] += int(v)
    gear = user_data.get("gear", {})
    if isinstance(gear, dict):
        for v in gear.values():
            if v: counts[str(v).lower()] += 1
    return counts

def get_user_collectibles(all_collectibles: List[Collectible], user_data: Dict) -> List[Collectible]:
    """Matches user owned collectible IDs to the loaded game data definitions."""
    user_owned_ids = set()
    
    # 1. Check the specific 'collectibles' list in JSON
    if "collectibles" in user_data and isinstance(user_data["collectibles"], list):
        for c_id in user_data["collectibles"]:
            user_owned_ids.add(str(c_id).lower())
            
    # 2. Also check bank/inventory just in case
    owned_objs = []
    for c in all_collectibles:
        if c.id.lower() in user_owned_ids or c.wiki_slug.lower() in user_owned_ids:
            owned_objs.append(c)
            
    return owned_objs

def filter_user_items(all_items: List[Equipment], user_data: Dict) -> List[Equipment]:
    try:
        owned_ids = set()
        counts = extract_user_counts(user_data)
        for k, v in counts.items():
            if v > 0: owned_ids.add(k)
        
        filtered_items = []
        for item in all_items:
            candidates = set()
            candidates.add(item.id.lower())
            if item.wiki_slug: candidates.add(item.wiki_slug.lower())
            if item.name: candidates.add(item.name.lower())
            base_id = item.id.lower()
            suffixes = ["_common", "_uncommon", "_rare", "_epic", "_legendary", "_ethereal", "_normal"]
            for s in suffixes:
                if base_id.endswith(s): candidates.add(base_id.replace(s, ""))
            
            if not owned_ids.isdisjoint(candidates):
                filtered_items.append(item)
        return filtered_items
    except Exception:
        return all_items

# --- Main App ---
def main():
    all_items_raw, activities, recipes, locations = load_data()   
    all_collectibles_raw = load_collectibles_data()
    
    WIKI_URL = "https://gear.walkscape.app"

    st.title("🛡️ WalkScape Gear Optimizer")

    # --- Inputs ---
    with st.container():
        with st.expander("📂 User Save Data & Settings", expanded=True):
            col_json, col_opts = st.columns([3, 1])
            with col_json:
                user_json_input = st.text_area(
                    "Paste User JSON", 
                    height=70, 
                    placeholder='{"name": "...", "skills": {...}, "collectibles": [...]}'
                )
            
            user_data = None
            calculated_char_lvl = 99
            user_skills_map = {}
            valid_json = False
            item_counts = {}
            user_ap = 0
            owned_collectibles = []

            if user_json_input.strip():
                try:
                    user_data = json.loads(user_json_input)
                    valid_json = True
                    steps = user_data.get("steps", 0)
                    calculated_char_lvl = calculate_char_level_from_steps(steps)
                    user_skills_map = user_data.get("skills", {})
                    user_ap = user_data.get("achievement_points", 0)
                    item_counts = extract_user_counts(user_data)
                    
                    if all_collectibles_raw:
                        owned_collectibles = get_user_collectibles(all_collectibles_raw, user_data)
                    
                    st.success(f"Loaded: {user_data.get('name', 'Player')} | Items: {len(item_counts)} | Collectibles: {len(owned_collectibles)} | AP: {user_ap}")
                except json.JSONDecodeError:
                    st.error("Invalid JSON")
            
            with col_opts:
                st.write("")
                use_owned = st.checkbox("Only use owned items", value=valid_json)

        c1, c2, c3 = st.columns([2, 1, 1])
        with c1:
            act_map = {a.name: a for a in activities}
            act_names = sorted(list(act_map.keys()))
            selected_act_name = st.selectbox("Select Activity", options=act_names, index=None, placeholder="Search activity...")
        
        with c2:
            target_options = {t.name.replace('_', ' ').title(): t for t in OPTIMAZATION_TARGET}
            selected_target_key = st.selectbox("Target Stat", options=list(target_options.keys()))
            selected_target = target_options[selected_target_key]
        
        with c3:
            st.write("")
            st.write("")
            # Updated to use width='stretch' to fix warning
            run_opt = st.button("🚀 Optimize", type="primary", use_container_width=True)

    st.divider()

    left_col, right_col = st.columns([1, 2.5])

    # --- WIKI ---
    with right_col:
        st.subheader("Wiki Reference")
        components.iframe(WIKI_URL, height=1200, scrolling=True)

    # --- RESULTS & DEBUGGER ---
    with left_col:
        st.subheader("Results")

        if use_owned and user_data:
            available_items = filter_user_items(all_items_raw, user_data)
        else:
            available_items = all_items_raw
            item_counts = None

        if run_opt and selected_act_name:
            activity = act_map[selected_act_name]
            player_lvl = calculated_char_lvl if valid_json else 99
            final_skill_lvl = 99
            if valid_json and activity.primary_skill:
                skill_key = activity.primary_skill.lower()
                skill_xp = user_skills_map.get(skill_key, 0)
                final_skill_lvl = calculate_level_from_xp(skill_xp)
            
            # Recreate optimizer fresh each run
            optimizer = GearOptimizer(available_items, all_locations=locations)
            
            # --- Optimize ---
            with st.spinner(f"Optimizing {selected_act_name}..."):
                best_gear = optimizer.optimize(
                    activity, 
                    player_level=player_lvl, 
                    player_skill_level=final_skill_lvl,
                    optimazation_target=selected_target,
                    owned_item_counts=item_counts if use_owned else None,
                    achievement_points=user_ap,
                    owned_collectibles=owned_collectibles
                )

                # Save session state
                st.session_state['best_gear'] = best_gear
                st.session_state['final_skill_lvl'] = final_skill_lvl
                st.session_state['selected_activity_name'] = selected_act_name
                st.session_state['debug_candidates'] = optimizer.debug_candidates
                st.session_state['debug_rejected'] = optimizer.debug_rejected
                st.session_state['owned_collectibles'] = owned_collectibles

                # Rebuild context for session
                req_kw = {} 
                for req in activity.requirements:
                    if req.type == "keyword_count" and req.target:
                         req_kw[req.target.lower().replace("_", " ").strip()] = req.value
                
                st.session_state['context'] = {
                    "skill": activity.primary_skill,
                    "location_id": activity.locations[0] if activity.locations else None,
                    "location_tags": {t.lower() for t in locations[0].tags} if activity.locations else set(),
                    "activity_id": activity.id,
                    "required_keywords": req_kw,
                    "achievement_points": user_ap
                }

        # --- Display Results ---
        if 'best_gear' in st.session_state:
            best_gear = st.session_state['best_gear']
            context = st.session_state['context']
            saved_skill_lvl = st.session_state.get('final_skill_lvl', 99)
            saved_act_name = st.session_state.get('selected_activity_name', selected_act_name)
            saved_collectibles = st.session_state.get('owned_collectibles', [])
            
            optimizer = GearOptimizer(available_items, all_locations=locations) 

            if saved_act_name in act_map:
                activity = act_map[saved_act_name]

                passive_stats = optimizer._calculate_passive_stats(saved_collectibles, context)

                score = optimizer.calculate_score(best_gear, activity, saved_skill_lvl, selected_target, context, passive_stats=passive_stats)
                
                # FIX: Use safe get logic instead of +=
                stats = best_gear.get_stats(context)
                for k, v in passive_stats.items():
                    stats[k] = stats.get(k, 0.0) + v

                final_steps = calculate_steps(
                    activity, saved_skill_lvl, 
                    stats.get("work_efficiency", 0), 
                    stats.get("flat_step_reduction", 0), 
                    stats.get("percent_step_reduction", 0)
                )

                # --- Metrics ---
                c1, c2 = st.columns(2)
                c1.metric("Steps", final_steps, delta=f"{activity.base_steps}", delta_color="inverse")
                c1.caption(f"Score: {score:.5f}")
                
                val_fmt = ""
                if selected_target.name == "fine":
                    val = stats.get('fine_material_finding', 0) * 100
                    val_fmt = f"{val:.1f}% Fine"
                elif selected_target.name == "xp":
                    val = stats.get('xp_percent', 0) * 100
                    val_fmt = f"{val:.1f}% XP"
                c2.metric("Target Stat", val_fmt)

                st.divider()

                # --- Loadout ---
                loadout_data = []
                for slot in ["Head", "Chest", "Legs", "Feet", "Back", "Cape", "Neck", "Hands", "Primary", "Secondary"]:
                    item = getattr(best_gear, slot.lower())
                    loadout_data.append({"Slot": slot, "Item": item.name if item else "-"})
                
                for i, ring in enumerate(best_gear.rings):
                    loadout_data.append({"Slot": f"Ring {i+1}", "Item": ring.name})
                for i, tool in enumerate(best_gear.tools):
                    loadout_data.append({"Slot": f"Tool {i+1}", "Item": tool.name})

                # Updated to use width='stretch' to fix warning
                st.dataframe(pd.DataFrame(loadout_data), hide_index=True, use_container_width=True)

                # --- Export Section ---
                st.markdown("---")
                
                with st.success("✅ **Export Ready**"):
                    export_json = export_gearset(best_gear)
                    st.caption("Hover over the top-right of the code block to copy!")
                    st.code(export_json, language="json")

                # --- DEBUGGER TABS ---
                st.markdown("---")
                with st.expander("🧪 Laboratory / Debugger", expanded=False):
                    
                    tab_exp, tab_cand = st.tabs(["Item Swapper", "🕵️ Candidate Inspector"])
                    
                    # TAB 1: Item Swapper
                    with tab_exp:
                        st.info("Manually swap an item to verify the calculation logic.")
                        d_col1, d_col2 = st.columns([1, 1])
                        
                        with d_col1:
                            slot_options = ["Head", "Chest", "Legs", "Feet", "Back", "Cape", "Neck", "Hands", "Primary", "Secondary", "Ring 1", "Ring 2", "Tool 1", "Tool 2", "Tool 3", "Tool 4", "Tool 5", "Tool 6"]
                            edit_slot = st.selectbox("Select Slot to Swap", options=slot_options)
                            
                            current_item_name = "-"
                            if "Tool" in edit_slot:
                                idx = int(edit_slot.split(" ")[1]) - 1
                                if idx < len(best_gear.tools): current_item_name = best_gear.tools[idx].name
                            elif "Ring" in edit_slot:
                                idx = int(edit_slot.split(" ")[1]) - 1
                                if idx < len(best_gear.rings): current_item_name = best_gear.rings[idx].name
                            else:
                                current_item_obj = getattr(best_gear, edit_slot.lower(), None)
                                if current_item_obj: current_item_name = current_item_obj.name
                            
                            st.caption(f"Currently Equipped: **{current_item_name}**")

                            slot_enum_map = {
                                "Head": "head", "Chest": "chest", "Legs": "legs", "Feet": "feet",
                                "Back": "back", "Cape": "cape", "Neck": "neck", "Hands": "hands",
                                "Primary": "primary", "Secondary": "secondary",
                                "Ring": "ring", "Tool": "tools"
                            }
                            target_enum = slot_enum_map.get(edit_slot.split(" ")[0])
                            
                            valid_swap_items = [i for i in available_items if i.slot == target_enum]
                            valid_swap_items.sort(key=lambda x: x.name)
                            
                            swap_item_name = st.selectbox("Swap with:", options=[i.name for i in valid_swap_items], index=None)
                            swap_item_obj = next((i for i in valid_swap_items if i.name == swap_item_name), None)

                        with d_col2:
                            if swap_item_obj:
                                test_gear = GearSet(**best_gear.dict())
                                test_gear.rings = list(best_gear.rings)
                                test_gear.tools = list(best_gear.tools)
                                
                                if "Tool" in edit_slot:
                                    idx = int(edit_slot.split(" ")[1]) - 1
                                    while len(test_gear.tools) <= idx: test_gear.tools.append(None)
                                    if idx < len(test_gear.tools): test_gear.tools[idx] = swap_item_obj
                                    else: test_gear.tools.append(swap_item_obj)
                                elif "Ring" in edit_slot:
                                    idx = int(edit_slot.split(" ")[1]) - 1
                                    while len(test_gear.rings) <= idx: test_gear.rings.append(None)
                                    if idx < len(test_gear.rings): test_gear.rings[idx] = swap_item_obj
                                    else: test_gear.rings.append(swap_item_obj)
                                else:
                                    setattr(test_gear, edit_slot.lower(), swap_item_obj)

                                analysis = optimizer.analyze_score(test_gear, activity, saved_skill_lvl, selected_target, context, passive_stats=passive_stats)
                                test_score = analysis.get("score", 0)
                                test_steps = analysis.get("denominator", 0)
                                test_formula = analysis.get("formula", "")

                                orig_analysis = optimizer.analyze_score(best_gear, activity, saved_skill_lvl, selected_target, context, passive_stats=passive_stats)
                                orig_score = orig_analysis.get("score", 0)
                                orig_steps = orig_analysis.get("denominator", 0)
                                orig_formula = orig_analysis.get("formula", "")

                                st.markdown("##### Comparison")
                                def show_diff(label, orig, new, is_good_up=True):
                                    diff = new - orig
                                    color = "off"
                                    if diff > 0: color = "green" if is_good_up else "red"
                                    elif diff < 0: color = "red" if is_good_up else "green"
                                    st.markdown(f"**{label}**: {orig:.4f} → **{new:.4f}** :{color}[({diff:+.4f})]")

                                show_diff("Score", orig_score, test_score, True)
                                show_diff("Steps", orig_steps, test_steps, False)
                                
                                st.markdown("**Formula Breakdown**")
                                st.text(f"Original: {orig_formula}")
                                st.text(f"New:      {test_formula}")
                                
                                st.markdown("---")
                                st.caption("Detailed Stat Changes (Including Collectibles):")
                                test_stats = analysis.get("stats", {})
                                orig_stats = orig_analysis.get("stats", {})
                                for k in ["fine_material_finding", "double_rewards", "double_action", "work_efficiency", "xp_percent", "percent_step_reduction"]:
                                    v1 = orig_stats.get(k, 0)
                                    v2 = test_stats.get(k, 0)
                                    if abs(v1-v2) > 0.001:
                                        st.text(f"{k}: {v1:.2f} -> {v2:.2f}")

                    # TAB 2: Candidate Inspector
                    with tab_cand:
                        st.write("Inspect which items passed the filter and their scores.")
                        insp_slot = st.selectbox("Inspect Slot", options=["tools", "ring", "head", "chest", "legs", "feet", "back", "cape", "neck", "hands", "primary", "secondary"])
                        
                        debug_candidates = st.session_state.get('debug_candidates', {})
                        debug_rejected = st.session_state.get('debug_rejected', [])
                        
                        # Passed Items
                        items = debug_candidates.get(insp_slot, [])
                        if items:
                            st.markdown(f"**✅ Accepted Candidates ({len(items)})**")
                            # Calculate scores for display
                            cand_data = []
                            for item in items:
                                # Create dummy set
                                d_set = GearSet()
                                if insp_slot == "tools": d_set.tools = [item]
                                elif insp_slot == "ring": d_set.rings = [item]
                                else: 
                                    attr = "hands" if insp_slot == "gloves" else insp_slot
                                    setattr(d_set, attr, item)
                                
                                s = optimizer.calculate_score(d_set, activity, saved_skill_lvl, selected_target, context, ignore_requirements=True)
                                cand_data.append({"Name": item.name, "Score": s, "ID": item.id})
                            
                            df_cand = pd.DataFrame(cand_data).sort_values(by="Score", ascending=False)
                            # Updated to use width='stretch' to fix warning
                            st.dataframe(df_cand, use_container_width=True)
                        else:
                            st.warning("No candidates found for this slot.")

                        # Rejected Items
                        st.markdown("---")
                        st.markdown("**❌ Rejected Items (Sample)**")
                        rejected_in_slot = [r for r in debug_rejected if r['slot'] == insp_slot]
                        if rejected_in_slot:
                             df_rej = pd.DataFrame(rejected_in_slot)
                             # Updated to use width='stretch' to fix warning
                             st.dataframe(df_rej, use_container_width=True)
                        else:
                            st.write("No items specifically rejected (all processed items passed or none checked).")

        elif not selected_act_name:
            st.info("👈 Select an activity to start.")
            
        else:
            st.write("Ready.")

if __name__ == "__main__":
    main()