import json
import csv
import time
import argparse
import multiprocessing
from concurrent.futures import ProcessPoolExecutor
from collections import defaultdict
from tqdm import tqdm  # <--- ADD THIS
# Import your existing logic
from utils.data_loader import load_game_data
from utils.constants import OPTIMAZATION_TARGET, EquipmentSlot
from models import CraftingNode, Recipe, Activity, GearSet
from drop_calculator import DropCalculator
from gear_optimizer import GearOptimizer
from calculations import calculate_passive_stats, analyze_score, _calculate_single_target_score
from ui_utils import build_activity_context, get_compatible_services, synthesize_activity_from_recipe, get_best_auto_pet

def load_all_game_data():
    """Helper to load all game data locally."""
    base_path = "game_data/wiki_export/autogenerated"
    return load_game_data(
        f"{base_path}/equipment.json", f"{base_path}/activities.json",
        f"{base_path}/recipes.json", f"{base_path}/locations.json",
        f"{base_path}/services.json", f"{base_path}/collectibles.json",
        f"{base_path}/materials.json"
    )

def worker_init():
    """Initializes global data per worker process so we don't have to pickle giant datasets."""
    global items, activities, recipes, locations, services, collectibles, materials, drop_calc, pets, optimizer_pool
    items, activities, recipes, locations, services, collectibles, materials = load_all_game_data()
    drop_calc = DropCalculator()
    optimizer_pool = GearOptimizer(items, locations)
    
    # Load pets 
    pets = []
    try:
        import os
        from models import Pet
        pets_path = "game_data/wiki_export/autogenerated/pets.json"
        if os.path.exists(pets_path):
            with open(pets_path, "r", encoding="utf-8") as f:
                for p_data in json.load(f): pets.append(Pet(**p_data))
    except Exception:
        pass


def process_job(job):
    """The heavy lifting function executed by the multiprocessing pool."""
    from ui_utils import extract_modifier_stats # Required for service buffs

    run_name = job['run_name']
    target_list = job['targets']
    obj_type = job['type']
    obj_id = job['id']
    is_fine = job['is_fine']
    service_id = job['service_id']
    location_id = job['location_id']
    
    # Setup user stats (theoretical max)
    user_ap = 10000
    user_total_level = 2000
    player_lvl = 99
    owned_item_counts = None 
    owned_collectibles = collectibles 
    extra_passive_stats = {}

    # 1. Resolve Activity/Recipe & Emulate UI's Wrapping
    if obj_type == "recipe":
        base_obj = next((r for r in recipes if r.id == obj_id), None)
        if service_id:
            srv = next((s for s in services if s.id == service_id), None)
            final_activity = synthesize_activity_from_recipe(base_obj, srv)
            location_id = srv.location
            # SILENT BUG FIX: Extract service stats
            extra_passive_stats = extract_modifier_stats(srv.modifiers)
        else:
            # CRASH FIX: Wrap the recipe exactly like the UI does
            class WrappedRecipe:
                def __init__(self, r):
                    self.id = r.id
                    self.name = r.name
                    self.primary_skill = r.skill
                    self.level = r.level
                    self.base_xp = r.base_xp
                    self.base_steps = r.base_steps
                    self.max_efficiency = r.max_efficiency
                    self.locations = []
                    self.requirements = r.requirements if hasattr(r, 'requirements') else []
                    self.materials = r.materials
                    self.output_item_id = r.output_item_id
                    self.output_quantity = r.output_quantity

            final_activity = WrappedRecipe(base_obj)
    else:
        final_activity = next((a for a in activities if a.id == obj_id), None)

    if not final_activity: return None

    # 2. SILENT BUG FIX: Calculate is_equipment_upgrade and base_input_cost
    is_equipment_upgrade = False
    base_input_cost = 0.0
    
    if obj_type == "recipe" and getattr(final_activity, 'materials', None):
        for i, mat_group in enumerate(final_activity.materials):
            base_id = mat_group[0].item_id.replace("_fine", "")
            mat_id = base_id
            
            # Rely on drop_calc's pre-computed map to safely check for fine variants
            has_fine_version = base_id in drop_calc.fine_material_map
            
            if is_fine and has_fine_version:
                mat_id = f"{base_id}_fine"
                
            base_input_cost += mat_group[0].amount * drop_calc.item_values.get(mat_id, 0.0)
            if not has_fine_version:
                is_equipment_upgrade = True

    # 3. Context setup
    loc_map = {loc.id: loc for loc in locations}
    context = build_activity_context(
        activity=final_activity, user_ap=user_ap, user_total_level=user_total_level,
        loc_map=loc_map, drop_calc=drop_calc, selected_location_id=location_id
    )
    
    # SILENT BUG FIX: Inject missing variables into context
    context["is_fine_materials"] = is_fine
    context["is_equipment_upgrade"] = is_equipment_upgrade 
    context["base_input_cost"] = base_input_cost            
    context["drop_calc"] = drop_calc  # Crucial for net_profit_per_step target!                  

    # 4. Auto-select Pet
    game_data_dict = {'recipes': {r.id: r for r in recipes}, 'activities': {a.id: a for a in activities}, 'pets': {p.id: p for p in pets}}
    dummy_node = CraftingNode(node_id="dummy", item_id="dummy", source_type=obj_type, source_id=obj_id, selected_location_id=location_id)
    best_pet_id, best_pet_lvl = get_best_auto_pet(dummy_node, game_data_dict, loc_map, drop_calc, user_ap, user_total_level, False, {})
    
    actual_pet = None
    if best_pet_id:
        p = next((p for p in pets if p.id == best_pet_id), None)
        if p: actual_pet = p.model_copy(update={"active_level": best_pet_lvl, "use_pet_ability": True})

    # 5. Run Optimization
    best_gear, error, _ = optimizer_pool.optimize(
        activity=final_activity, player_level=99, player_skill_level=99,
        optimazation_target=target_list, owned_item_counts=owned_item_counts,
        achievement_points=user_ap, user_reputation=None, owned_collectibles=owned_collectibles,
        extra_passive_stats=extra_passive_stats, context_override=context, pet=actual_pet, consumable=None,
        locked_items={}, blacklisted_ids=set()
    )

    if error or not best_gear:
        return None

    # Calculate final stats and raw metrics for CSV
    passive_stats = calculate_passive_stats(owned_collectibles, context)
    final_stats = best_gear.get_stats(context)
    for k, v in passive_stats.items(): final_stats[k] = final_stats.get(k, 0.0) + v
    for k, v in extra_passive_stats.items(): final_stats[k] = final_stats.get(k, 0.0) + v # Make sure service stats reflect in the final CSV output

    # Extract human-readable metrics dynamically using your logic
    xp_per_step = _calculate_single_target_score(OPTIMAZATION_TARGET.xp, final_activity, 99, final_stats, context)
    coins_per_step = _calculate_single_target_score(OPTIMAZATION_TARGET.coins, final_activity, 99, final_stats, context)
    out_in_ratio = _calculate_single_target_score(OPTIMAZATION_TARGET.materials_from_input, final_activity, 99, final_stats, context)
    steps_per_action = _calculate_single_target_score(OPTIMAZATION_TARGET.reward_rolls, final_activity, 99, final_stats, context)
    actual_steps = 1.0 / steps_per_action if steps_per_action > 0 else 0

    row = {
        "Run Target": run_name,
        "Name": final_activity.name,
        "Type": obj_type.title(),
        "Skill": final_activity.primary_skill.title(),
        "Location": location_id if location_id else "Any",
        "Input Variant": "Fine" if is_fine else "Normal",
        "Pet": actual_pet.name if actual_pet else "None",
        "Tools": " | ".join([t.name for t in best_gear.tools]),
        "Rings": " | ".join([r.name for r in best_gear.rings]),
        "Head": best_gear.head.name if best_gear.head else "",
        "Chest": best_gear.chest.name if best_gear.chest else "",
        "Legs": best_gear.legs.name if best_gear.legs else "",
        "Primary": best_gear.primary.name if best_gear.primary else "",
        "Secondary": best_gear.secondary.name if best_gear.secondary else "",
        # Metrics
        "Base Steps": getattr(final_activity, 'base_steps', 0),
        "Final Steps/Action": round(actual_steps, 2),
        "XP/Step": round(xp_per_step, 4),
        "Coins/1k Steps": round(coins_per_step * 1000, 2),
        "Output/Input Ratio": round(out_in_ratio, 4),
        "Work Efficiency %": round(final_stats.get('work_efficiency', 0) * 100, 2),
        "Double Action %": round(final_stats.get('double_action', 0) * 100, 2),
        "Double Rewards %": round(final_stats.get('double_rewards', 0) * 100, 2),
        "No Mats Consumed %": round(final_stats.get('no_materials_consumed', 0) * 100, 2),
        "Quality Outcome": round(final_stats.get('quality_outcome', 0), 2),
    }
    
    return row
def generate_jobs(config):
    """Creates the matrix of combinations to evaluate."""
    # Temporarily load data just to build the job list
    _, activities, recipes, locations, services, _, _ = load_all_game_data()
    
    jobs = []
    for run in config['runs']:
        run_name = run['run_name']
        
        # Convert string targets to Enums
        target_list = []
        for t in run['targets']:
            enum_val = OPTIMAZATION_TARGET[t['name']]
            target_list.append((enum_val, float(t['weight'])))

        # 1. Activities
        for act in activities:
            locs = act.locations if act.locations else [None]
            for loc in locs:
                jobs.append({
                    "run_name": run_name, "targets": target_list, "type": "activity",
                    "id": act.id, "is_fine": False, "service_id": None, "location_id": loc
                })

        # 2. Recipes
        for rec in recipes:
            if rec.service.lower() != "none":
                compat_services = get_compatible_services(rec, services)
                for srv in compat_services:
                    jobs.append({
                        "run_name": run_name, "targets": target_list, "type": "recipe",
                        "id": rec.id, "is_fine": False, "service_id": srv.id, "location_id": None
                    })
                    jobs.append({
                        "run_name": run_name, "targets": target_list, "type": "recipe",
                        "id": rec.id, "is_fine": True, "service_id": srv.id, "location_id": None
                    })
            else:
                jobs.append({
                    "run_name": run_name, "targets": target_list, "type": "recipe",
                    "id": rec.id, "is_fine": False, "service_id": None, "location_id": None
                })
                jobs.append({
                    "run_name": run_name, "targets": target_list, "type": "recipe",
                    "id": rec.id, "is_fine": True, "service_id": None, "location_id": None
                })
                
    return jobs

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="WalkScape Gear Benchmark Tool")
    parser.add_argument("--config", default="brute_force_config.json", help="Path to JSON config file")
    args = parser.parse_args()

    with open(args.config, "r") as f:
        config = json.load(f)

    jobs = generate_jobs(config)
    print(f"Generated {len(jobs)} optimization permutations.")
    
    start_time = time.time()
    results = []

    # Multiprocessing Execution
    # By default, ProcessPoolExecutor uses all available CPU cores.
    with ProcessPoolExecutor(initializer=worker_init) as executor:
        
        # Wrap the map function in tqdm() for a beautiful progress bar and ETA
        for res in tqdm(executor.map(process_job, jobs), total=len(jobs), desc="Optimizing Gear"):
            if res:
                results.append(res)
  

    # Write to CSV
    if results:
        keys = results[0].keys()
        with open("benchmark_results.csv", "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(results)
            
        print(f"\nDone! Exported {len(results)} rows to benchmark_results.csv")
    else:
        print("\nNo valid results generated.")
        
    print(f"Total execution time: {round(time.time() - start_time, 2)} seconds")