import json
from models import Activity

# Check 1: raw JSON
with open('game_data/wiki_export/autogenerated/activities.json', 'r', encoding='utf-8') as f:
    act_data = json.load(f)

bird = next((a for a in act_data if a.get('id') == 'bird_watching'), None)
print('=== RAW JSON fields ===')
print('base_steps:', bird.get('base_steps'))
print('max_efficiency:', bird.get('max_efficiency'))

# Check 2: Pydantic instantiation
act = Activity(**bird)
print('\n=== Activity object ===')
print('base_steps:', act.base_steps)
print('max_efficiency:', act.max_efficiency)
print('level:', act.level)

# Check 3: model_dump()
d = act.model_dump()
print('\n=== model_dump() ===')
print('base_steps:', d.get('base_steps'))
