import json
import os
from typing import Dict, List, Any, Optional, Set, Tuple

# Import the exact step calculation logic used in the optimizer
from calculations import calculate_steps, calculate_quality_probabilities
from utils.constants import SPECIAL_FIND_MAP, QUALITY_SUFFIX_MAP

# ===========================================================================
# STATIC DATA
# ===========================================================================

class DropCalculator:
    def __init__(self):
        self.fine_material_map: Dict[str, str] = {} 
        self.chest_ids: Set[str] = set()
        self.collectible_ids: Set[str] = set()
        
        self.item_values: Dict[str, float] = {"coins": 1.0}
        self.container_evs: Dict[str, float] = {}
        
        # Base path for data files
        self.data_dir = "game_data/wiki_export/autogenerated"
        self._load_data()

    def _load_data(self):
        """
        Loads necessary JSON files to determine item properties.
        Attempts to load from the standard path, falling back to local if needed.
        """
        files_to_load = {
            "equipment": "equipment.json",
            "materials": "materials.json",
            "consumables": "consumables.json",
            "containers": "containers.json",
            "collectibles": "collectibles.json"
        }
        
        loaded_data = {}

        for key, filename in files_to_load.items():
            # Try 1: Standard Path
            path = os.path.join(self.data_dir, filename)
            if not os.path.exists(path):
                # Try 2: Local Path (Fallback)
                path = filename
            
            try:
                if os.path.exists(path):
                    with open(path, 'r', encoding='utf-8') as f:
                        loaded_data[key] = json.load(f)
                else:
                    loaded_data[key] = []
            except Exception as e:
                print(f"Error loading {filename}: {e}")
                loaded_data[key] = []

        # Process Loaded Data
        all_items = loaded_data.get("equipment", []) + loaded_data.get("materials", []) + loaded_data.get("consumables", [])
        containers = loaded_data.get("containers", [])
        collectibles = loaded_data.get("collectibles", [])

        # 1. Map Fine Materials
        all_ids = {item.get("id") for item in all_items}
        for item in all_items:
            i_id = item.get("id")
            fine_id = f"{i_id}_fine"
            if fine_id in all_ids:
                self.fine_material_map[i_id] = fine_id

        # 2. Identify Chests
        for c in containers:
            c_id = c.get("id")
            if c_id and c_id != "bird_nest":
                self.chest_ids.add(c_id)

        # 3. Identify Collectibles
        for c in collectibles:
            c_id = c.get("id")
            if c_id:
                self.collectible_ids.add(c_id)

        for item in all_items:
            i_id = item.get("id")
            if i_id:
                self.item_values[i_id] = float(item.get("value", 0))
                
        for c in containers:
            c_id = c.get("id")
            if c_id:
                self.container_evs[c_id] = float(c.get("total_expected_value", 0.0))

    def get_drop_table(self, activity: Any, stats: Dict[str, float], 
                       player_skill_lvl: int, is_fine_materials: bool = False, 
                       is_equipment_upgrade: bool = False) -> List[Dict[str, Any]]:
        rows = []
        
        # 1. Calculate Steps
        work_eff = stats.get("work_efficiency", 0.0)
        flat_step_red = int(stats.get("flat_step_reduction", 0))
        pct_step_red = stats.get("percent_step_reduction", 0.0)
        
        action_steps = calculate_steps(
            activity, 
            player_skill_lvl, 
            work_eff, 
            flat_step_red, 
            pct_step_red
        )
        
        # 2. Reward Logic
        da_val = stats.get("double_action", 0.0)
        dr_val = stats.get("double_rewards", 0.0)
        
        # Total multiplier for frequency of rolls
        steps_per_roll = action_steps / ((1.0 + da_val) * (1.0 + dr_val))

        # --- EXTRACT FINE CONVERSION RATE ---
        fine_bonus = stats.get("fine_material_finding", 0.0)
        fine_conversion_rate = min(1.0, 0.01 * (1.0 + fine_bonus))

        is_recipe = getattr(activity, "output_item_id", None) is not None

        if is_recipe:
            # ==========================================
            # RECIPE OUTPUTS
            # ==========================================
            base_id = activity.output_item_id
            avg_quantity = float(activity.output_quantity)
            
            # Detect if this is an equipment item by checking if a "Good" (_uncommon) or "Normal" (_common) variant exists in game data
            is_equipment = f"{base_id}_uncommon" in self.item_values or f"{base_id}_common" in self.item_values

            if is_equipment:
                quality_bonus = stats.get("quality_outcome", 0.0)
                probs = calculate_quality_probabilities(
                    activity.level, player_skill_lvl, quality_bonus,
                    is_fine_materials=is_fine_materials,
                    is_equipment_upgrade=is_equipment_upgrade
                )
                
                for qual_name, prob in probs.items():
                    if prob > 0:
                        suffix = QUALITY_SUFFIX_MAP.get(qual_name, "")
                        q_id = f"{base_id}{suffix}"
                        
                        # Fallback for base items that might not use the _common suffix natively
                        if q_id not in self.item_values and qual_name == "Normal":
                            q_id = base_id
                            
                        self._add_row(rows, q_id, prob, steps_per_roll, avg_quantity)
            else:
                # Material or Consumable Output
                if is_fine_materials:
                    fine_id = self.fine_material_map.get(base_id, f"{base_id}_fine")
                    self._add_row(rows, fine_id, 1.0, steps_per_roll, avg_quantity)
                else:
                    fine_id = self.fine_material_map.get(base_id)
                    if fine_id and fine_conversion_rate > 0:
                        self._add_row(rows, base_id, 1.0 - fine_conversion_rate, steps_per_roll, avg_quantity)
                        self._add_row(rows, fine_id, fine_conversion_rate, steps_per_roll, avg_quantity)
                    else:
                        self._add_row(rows, base_id, 1.0, steps_per_roll, avg_quantity)

            # Recipe Specific Chest Drop (1/250 Base Chance)
            activity_skill = getattr(activity, "primary_skill", getattr(activity, "skill", ""))
            chest_id = f"{activity_skill}_chest"
            base_chest_chance = 0.004
            chest_multiplier = 1.0 + stats.get("chest_finding", 0.0)
            final_chest_prob = base_chest_chance * chest_multiplier
            self._add_row(rows, chest_id, final_chest_prob, steps_per_roll, 1.0)
            
        else:
            # ==========================================
            # ACTIVITY OUTPUTS
            # ==========================================
            act_dict = activity.model_dump() if hasattr(activity, "model_dump") else activity.__dict__
            loot_tables = act_dict.get("loot_tables", [])

            for table in loot_tables:
                rolls = table.get("rolls", 1)
                table_type = table.get("type", "main")
                drops = table.get("drops", [])
                
                for drop in drops:
                    item_id = drop.get("item_id")
                    base_chance = drop.get("chance", 0.0)
                    
                    min_q = drop.get("min_quantity", 1)
                    max_q = drop.get("max_quantity", 1)
                    avg_quantity = (min_q + max_q) / 2.0
                    
                    if item_id == "nothing" or base_chance <= 0:
                        continue

                    multiplier = 1.0

                    # Check Modifiers
                    if item_id in self.chest_ids:
                        multiplier += stats.get("chest_finding", 0.0)
                    if item_id == "bird_nest":
                        multiplier += stats.get("find_bird_nests", 0.0)
                    if item_id in self.collectible_ids:
                        multiplier += stats.get("find_collectibles", 0.0)
                    if table_type == "gem":
                         multiplier += stats.get("find_gems", 0.0)

                    final_prob = (base_chance / 100.0) * multiplier * rolls

                    # Check Fine Material
                    fine_id = self.fine_material_map.get(item_id)
                    if fine_id:
                        prob_fine = final_prob * fine_conversion_rate
                        prob_normal = final_prob * (1.0 - fine_conversion_rate)

                        self._add_row(rows, item_id, prob_normal, steps_per_roll, avg_quantity)
                        self._add_row(rows, fine_id, prob_fine, steps_per_roll, avg_quantity)
                    else:
                        self._add_row(rows, item_id, final_prob, steps_per_roll, avg_quantity)

        # ==========================================
        # SPECIAL FINDS (Shared by Recipes & Activities)
        # ==========================================
        for stat_key, reward_data in SPECIAL_FIND_MAP.items():
            chance = stats.get(stat_key, 0.0)
            if chance <= 0:
                continue

            if isinstance(reward_data, list):
                for tuple_data in reward_data:
                    if len(tuple_data) == 3:
                        sub_item, sub_weight, sub_qty = tuple_data
                    else:
                        sub_item, sub_weight = tuple_data
                        sub_qty = 1.0
                    
                    final_prob = chance * sub_weight
                    fine_id = self.fine_material_map.get(sub_item)
                    
                    if fine_id:
                        self._add_row(rows, sub_item, final_prob * (1.0 - fine_conversion_rate), steps_per_roll, sub_qty)
                        self._add_row(rows, fine_id, final_prob * fine_conversion_rate, steps_per_roll, sub_qty)
                    else:
                        self._add_row(rows, sub_item, final_prob, steps_per_roll, sub_qty)
            else:
                fine_id = self.fine_material_map.get(reward_data)
                
                if fine_id:
                    self._add_row(rows, reward_data, chance * (1.0 - fine_conversion_rate), steps_per_roll, 1.0)
                    self._add_row(rows, fine_id, chance * fine_conversion_rate, steps_per_roll, 1.0)
                else:
                    self._add_row(rows, reward_data, chance, steps_per_roll, 1.0)

        return rows
    
    def get_special_ev_map(self) -> Dict[str, Dict[str, float]]:
        """Returns the normal and fine expected value for every stat in SPECIAL_FIND_MAP."""
        from utils.constants import SPECIAL_FIND_MAP
        
        ev_map = {}
        
        def get_ev(item_id):
            if item_id in self.container_evs:
                ev = self.container_evs[item_id]
                return ev, ev 
            norm = self.item_values.get(item_id, 0.0)
            fine = self.item_values.get(f"{item_id}_fine", norm)
            return norm, fine

        for stat_key, reward_data in SPECIAL_FIND_MAP.items():
            if isinstance(reward_data, list):
                norm_tot, fine_tot = 0.0, 0.0
                for tuple_data in reward_data:
                    if len(tuple_data) == 3:
                        sub_item, weight, qty = tuple_data
                    else:
                        sub_item, weight = tuple_data
                        qty = 1.0
                    n, f = get_ev(sub_item)
                    norm_tot += n * weight * qty
                    fine_tot += f * weight * qty
                ev_map[stat_key] = {"normal": norm_tot, "fine": fine_tot}
            else:
                n, f = get_ev(reward_data)
                ev_map[stat_key] = {"normal": n, "fine": f}
        
        return ev_map

    def _add_row(self, rows: List[Dict], item_id: str, prob: float, steps_per_roll: float, avg_quantity: float):
        if prob <= 0: 
            return
            
        # Steps per Item = (Steps per Roll) / (Probability * Quantity)
        steps_for_drop = steps_per_roll / (prob * avg_quantity)
        
        rows.append({
            "Item": item_id,
            "Steps": steps_for_drop
        })