import json
import os
from typing import Dict, List, Any, Optional, Set, Tuple

# Import the exact step calculation logic used in the optimizer
from calculations import calculate_steps
from utils.constants import SPECIAL_FIND_MAP

# ===========================================================================
# STATIC DATA
# ===========================================================================


class DropCalculator:
    def __init__(self):
        self.fine_material_map: Dict[str, str] = {} 
        self.chest_ids: Set[str] = set()
        self.collectible_ids: Set[str] = set()
        
        # Base path for data files
        self.data_dir = "game_data/wiki_export/autogenerated"
        self._load_data()

    def _load_data(self):
        """
        Loads necessary JSON files to determine item properties.
        Attempts to load from the standard path, falling back to local if needed.
        """
        files_to_load = {
            "materials": "materials.json",
            "consumables": "consumables.json",
            "containers": "containers.json",
            "collectibles": "collectibles.json"
        }
        
        loaded_data = {}

        for key, filename in files_to_load.items():
            # Try 1: Standard Path
            path = os.path.join(self.data_dir, filename)
            if not os.path.exists(path):
                # Try 2: Local Path (Fallback)
                path = filename
            
            try:
                if os.path.exists(path):
                    with open(path, 'r', encoding='utf-8') as f:
                        loaded_data[key] = json.load(f)
                else:
                    # Fail silently or log if needed; empty lists handle missing data gracefully
                    loaded_data[key] = []
            except Exception as e:
                print(f"Error loading {filename}: {e}")
                loaded_data[key] = []

        # Process Loaded Data
        all_items = loaded_data.get("materials", []) + loaded_data.get("consumables", [])
        containers = loaded_data.get("containers", [])
        collectibles = loaded_data.get("collectibles", [])

        # 1. Map Fine Materials
        all_ids = {item.get("id") for item in all_items}
        for item in all_items:
            i_id = item.get("id")
            fine_id = f"{i_id}_fine"
            if fine_id in all_ids:
                self.fine_material_map[i_id] = fine_id

        # 2. Identify Chests
        for c in containers:
            c_id = c.get("id")
            if c_id and c_id != "bird_nest":
                self.chest_ids.add(c_id)

        # 3. Identify Collectibles
        for c in collectibles:
            c_id = c.get("id")
            if c_id:
                self.collectible_ids.add(c_id)

    def get_drop_table(self, activity: Any, stats: Dict[str, float], 
                       player_skill_lvl: int) -> List[Dict[str, Any]]:
        rows = []
        
        # 1. Calculate Steps
        work_eff = stats.get("work_efficiency", 0.0)
        flat_step_red = int(stats.get("flat_step_reduction", 0))
        pct_step_red = stats.get("percent_step_reduction", 0.0)
        
        action_steps = calculate_steps(
            activity, 
            player_skill_lvl, 
            work_eff, 
            flat_step_red, 
            pct_step_red
        )
        
        # 2. Reward Logic
        da_val = stats.get("double_action", 0.0)
        # Fix: Double Rewards logic now matches Wiki: (1 + DA) * (1 + DR)
        dr_val = stats.get("double_rewards", 0.0)
        
        # Total multiplier for output quantity (not frequency)
        # This reduces steps per effective item
        steps_per_roll = action_steps / ((1.0 + da_val) * (1.0 + dr_val))

        # 3. Process Standard Loot Tables
        act_dict = activity.model_dump() if hasattr(activity, "model_dump") else activity.__dict__
        loot_tables = act_dict.get("loot_tables", [])

        for table in loot_tables:
            table_type = table.get("type", "main")
            drops = table.get("drops", [])
            
            for drop in drops:
                item_id = drop.get("item_id")
                base_chance = drop.get("chance", 0.0)
                
                # Fix: Handle Quantity
                min_q = drop.get("min_quantity", 1)
                max_q = drop.get("max_quantity", 1)
                avg_quantity = (min_q + max_q) / 2.0
                
                if item_id == "nothing" or base_chance <= 0:
                    continue

                multiplier = 1.0

                # Check Modifiers
                if item_id in self.chest_ids:
                    multiplier += stats.get("chest_finding", 0.0)
                
                # Fix: Add Bird Nest Logic
                if item_id == "bird_nest":
                    multiplier += stats.get("find_bird_nests", 0.0)

                if item_id in self.collectible_ids:
                    multiplier += stats.get("find_collectibles", 0.0)
                
                if table_type == "gem":
                     multiplier += stats.get("find_gems", 0.0)

                final_prob = (base_chance / 100.0) * multiplier

                # Check Fine Material
                fine_id = self.fine_material_map.get(item_id)
                if fine_id:
                    fine_bonus = stats.get("fine_material_finding", 0.0)
                    # Note: Fine material finding is treated as a conversion chance here
                    fine_conversion_rate = min(1.0, 0.01 * (1.0 + fine_bonus))
                    
                    prob_fine = final_prob * fine_conversion_rate
                    prob_normal = final_prob * (1.0 - fine_conversion_rate)

                    self._add_row(rows, item_id, prob_normal, steps_per_roll, avg_quantity)
                    self._add_row(rows, fine_id, prob_fine, steps_per_roll, avg_quantity)
                else:
                    self._add_row(rows, item_id, final_prob, steps_per_roll, avg_quantity)

        # 4. Process Special Finds
        for stat_key, reward_data in SPECIAL_FIND_MAP.items():
            stat_val = stats.get(stat_key, 0.0)
            if stat_val <= 0:
                continue

            chance = stat_val / 100.0 

            if isinstance(reward_data, list):
                for sub_item, sub_weight in reward_data:
                    self._add_row(rows, sub_item, chance * sub_weight, steps_per_roll, 1.0)
            else:
                self._add_row(rows, reward_data, chance, steps_per_roll, 1.0)

        return rows

    def _add_row(self, rows: List[Dict], item_id: str, prob: float, steps_per_roll: float, avg_quantity: float):
        if prob <= 0: 
            return
            
        # Steps per Item = (Steps per Roll) / (Probability * Quantity)
        steps_for_drop = steps_per_roll / (prob * avg_quantity)
        
        rows.append({
            "Item": item_id,
            "Steps": steps_for_drop
        })
