import json
from typing import List, Tuple
from models import Equipment, Activity, Recipe, Location, Service, Collectible


def load_game_data(
    items_path: str = "game_data/wiki_export/autogenerated/equipment.json",
    activities_path: str = "game_data/wiki_export/autogenerated/activities.json",
    recipes_path: str = "game_data/wiki_export/autogenerated/recipes.json",
    locations_path: str = "game_data/wiki_export/autogenerated/locations.json",
    services_path: str = "game_data/wiki_export/autogenerated/services.json",
    collectibles_path: str = "game_data/wiki_export/autogenerated/collectibles.json",
) -> Tuple[List[Equipment], List[Activity], List[Recipe], List[Location],List[Service], List[Collectible]]:
    
    # Load Equipment
    with open(items_path, "r", encoding="utf-8") as f:
        items_data = json.load(f)
        all_items = [Equipment(**item) for item in items_data]

    # Load Activities
    with open(activities_path, "r", encoding="utf-8") as f:
        act_data = json.load(f)
        all_activities = [Activity(**act) for act in act_data]

    # Load Recipes
    with open(recipes_path, "r", encoding="utf-8") as f:
        rec_data = json.load(f)
        all_recipes = [Recipe(**rec) for rec in rec_data]

    # Load Locations (New)
    try:
        with open(locations_path, "r", encoding="utf-8") as f:
            loc_data = json.load(f)
            all_locations = [Location(**loc) for loc in loc_data]
    except FileNotFoundError:
        print("Warning: locations.json not found. Environment filtering will be limited.")
        all_locations = []

    # Load Services
    with open(services_path, "r", encoding="utf-8") as f:
        serv_data = json.load(f)
        all_services = [Service(**serv) for serv in serv_data]

    # Load Collectibles
    with open(collectibles_path, "r", encoding="utf-8") as f:
        coll_data = json.load(f)
        all_collectibles = [Collectible(**coll) for coll in coll_data]

    return all_items, all_activities, all_recipes, all_locations, all_services, all_collectibles